APP_NAME="RAG Document Intelligence"
APP_VERSION="0.1"

FILE_ALLOWED_TYPES='["text/plain", "application/pdf"]'
FILE_MAX_SIZE=10
FILE_DEFAULT_CHUNK_SIZE=512000

POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="postgres_password"
POSTGRES_HOST="pgvector"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="minirag"

# Choose CLOUD, or OLLAMA for a Mac-hosted/Colab-ngrok Ollama endpoint.
LLM_MODE="CLOUD"
OLLAMA_API_URL="http://host.docker.internal:11434/v1"
OLLAMA_GENERATION_MODEL_ID="llama3.2"
OLLAMA_EMBEDDING_MODEL_ID="nomic-embed-text"
OLLAMA_EMBEDDING_MODEL_SIZE=768

# Required only when LLM_MODE="CLOUD". Never commit a real key.
CLOUD_OPENAI_API_KEY=""
CLOUD_OPENAI_API_URL=""
CLOUD_GENERATION_MODEL_ID="gpt-4.1-mini"
CLOUD_EMBEDDING_MODEL_ID="text-embedding-3-small"
CLOUD_EMBEDDING_MODEL_SIZE=1536
GENERATION_MODEL_ID_LITERAL='["gpt-4.1-mini", "llama3.2"]'

INPUT_DAFAULT_MAX_CHARACTERS=1024
GENERATION_DAFAULT_MAX_TOKENS=200
GENERATION_DAFAULT_TEMPERATURE=0.1

VECTOR_DB_BACKEND_LITERAL='["QDRANT", "PGVECTOR"]'
VECTOR_DB_BACKEND="PGVECTOR"
VECTOR_DB_PATH="qdrant_db"
VECTOR_DB_DISTANCE_METHOD="cosine"
VECTOR_DB_PGVEC_INDEX_THRESHOLD=100

PRIMARY_LANG="en"
DEFAULT_LANG="en"

# Background processing inside the Docker network. Keep these values aligned
# with .env.rabbitmq and .env.redis after copying the templates.
CELERY_BROKER_URL="amqp://rag_user:change-me@rabbitmq:5672/rag_vhost"
CELERY_RESULT_BACKEND="redis://:change-me@redis:6379/0"
CELERY_TASK_SERIALIZER="json"
CELERY_TASK_TIME_LIMIT=600
CELERY_TASK_ACKS_LATE=false
CELERY_WORKER_CONCURRENCY=2
CELERY_FLOWER_PASSWORD="change-me"
